# Generated by Django 3.2.16 on 2023-03-16 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TB_Grupo',
            fields=[
                ('idGrupo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TB_Grupo',
            },
        ),
        migrations.CreateModel(
            name='TB_Localizacao',
            fields=[
                ('idLocalizacao', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('nome', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'TB_Localizacao',
            },
        ),
        migrations.CreateModel(
            name='TB_Modalidade',
            fields=[
                ('idModalidade', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('grupo', models.BooleanField(default=True)),
                ('pontuacao', models.IntegerField(default='1')),
                ('fotoModalidade', models.ImageField(blank=True, null=True, upload_to='iconsModalidades')),
            ],
            options={
                'db_table': 'TB_Modalidade',
            },
        ),
        migrations.CreateModel(
            name='TB_Sexo',
            fields=[
                ('idSexo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'TB_Sexo',
            },
        ),
        migrations.CreateModel(
            name='TB_Usuario',
            fields=[
                ('idUsuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('dataNascimento', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('fotoPerfil', models.ImageField(blank=True, null=True, upload_to='usuarios')),
                ('sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tb_sexo')),
            ],
            options={
                'db_table': 'TB_Usuario',
            },
        ),
        migrations.CreateModel(
            name='TB_LocalizacaoFavorito',
            fields=[
                ('idLocalizacaoFavorito', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tb_localizacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tb_usuario')),
            ],
            options={
                'db_table': 'TB_LocalizacaoFavorito',
            },
        ),
        migrations.CreateModel(
            name='TB_Jogo',
            fields=[
                ('idJogo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('dataHora', models.DateTimeField()),
                ('privado', models.BooleanField(default=False)),
                ('informacoes', models.TextField(blank=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='core.tb_grupo')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='core.tb_localizacao')),
            ],
            options={
                'db_table': 'TB_Jogo',
            },
        ),
        migrations.AddField(
            model_name='tb_grupo',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tb_usuario'),
        ),
        migrations.AddField(
            model_name='tb_grupo',
            name='modalidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tb_modalidade'),
        ),
        migrations.CreateModel(
            name='TB_EsporteFavorito',
            fields=[
                ('idEsporteFavorito', models.BigAutoField(primary_key=True, serialize=False)),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tb_modalidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esportesFavoritos', to='core.tb_usuario')),
            ],
            options={
                'db_table': 'TB_EsporteFavorito',
            },
        ),
        migrations.CreateModel(
            name='TB_Confirmado',
            fields=[
                ('idConfirmado', models.BigAutoField(primary_key=True, serialize=False)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmados', to='core.tb_jogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tb_usuario')),
            ],
            options={
                'db_table': 'TB_Confirmado',
            },
        ),
        migrations.CreateModel(
            name='TB_Acesso',
            fields=[
                ('idAcesso', models.BigAutoField(primary_key=True, serialize=False)),
                ('aprovado', models.BooleanField(default=False)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='core.tb_grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tb_usuario')),
            ],
            options={
                'db_table': 'TB_Acesso',
            },
        ),
        migrations.CreateModel(
            name='TA_Localizacao_Modalidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLocalizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalidades', to='core.tb_localizacao')),
                ('idModalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tb_modalidade')),
            ],
            options={
                'db_table': 'TA_Localizacao_Modalidades',
            },
        ),
    ]
